/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "broadcast": {                                   "en": "Broadcast",                                       "de": "Rundfunk",                                        "ru": "транслировать",                                   "pt": "transmissão",                                     "nl": "uitzending",                                      "fr": "diffuser",                                        "it": "trasmissione",                                    "es": "transmisión",                                     "pl": "audycja",                                         "zh-cn": "播送"},
    "controller_setup": {                            "en": "Controllers / Wiegand Bus Settings",              "de": "Controller / Wiegand-Bus-Einstellungen",          "ru": "Настройки контроллера и шины Wiegand",            "pt": "Configurações do controlador e do barramento Wiegand", "nl": "Controller- en Wiegand-businstellingen",          "fr": "Paramètres du contrôleur et du bus Wiegand",      "it": "Impostazioni del controller e del bus Wiegand",   "es": "Configuración del controlador y del bus Wiegand", "pl": "Ustawienia kontrolera i magistrali Wiegand",      "zh-cn": "控制器/韦根总线设置"},
    "controllers_info": {                            "en": "Settings for Controllers (Network and Interface)", "de": "Einstellungen für Controller (Netzwerk und Schnittstelle)", "ru": "Настройки контроллера и адреса получателя",       "pt": "Configurações para o endereço do controlador e do destinatário", "nl": "Instellingen voor controller en ontvangeradres",  "fr": "Paramètres pour le contrôleur et l'adresse du destinataire", "it": "Impostazioni per il controller e l'indirizzo del destinatario", "es": "Ajustes para la dirección del controlador y del destinatario", "pl": "Ustawienia dla kontrolera i adresu odbiorcy",     "zh-cn": "控制器和收件人地址的设置"},
    "controllers_title": {                           "en": "Controllers Settings",                            "de": "Controller-Einstellungen",                        "ru": "настройки контроллера",                           "pt": "configurações do controlador",                    "nl": "controller instellingen",                         "fr": "paramètres du contrôleur",                        "it": "impostazioni del controller",                     "es": "configuración del controlador",                   "pl": "ustawienia kontrolera",                           "zh-cn": "控制器设置"},
    "deviceIp": {                                    "en": "Controllers IP",                                  "de": "Controller-IP",                                   "ru": "IP контроллера",                                  "pt": "IP do controlador",                               "nl": "IP-controller",                                   "fr": "IP du contrôleur",                                "it": "IP del controllore",                              "es": "IP del controlador",                              "pl": "Adres IP kontrolera",                             "zh-cn": "控制器 IP"},
    "enabled": {                                     "en": "Activated",                                       "de": "Aktiviert",                                       "ru": "активирован",                                     "pt": "ativado",                                         "nl": "geactiveerd",                                     "fr": "activé",                                          "it": "attivato",                                        "es": "activado",                                        "pl": "aktywowany",                                      "zh-cn": "活性"},
    "exposedIp": {                                   "en": "Exposed Host IP",                                 "de": "Offengelegte Host-IP",                            "ru": "IP-адрес получателя",                             "pt": "IP do receptor",                                  "nl": "Ontvanger IP",                                    "fr": "IP du récepteur",                                 "it": "IP ricevitore",                                   "es": "IP del receptor",                                 "pl": "IP odbiorcy",                                     "zh-cn": "接收器 IP"},
    "exposedPort": {                                 "en": "Exposed Host Port",                               "de": "Offengelegter Host-Port",                         "ru": "Открытый хост-порт",                              "pt": "Porta do host exposta",                           "nl": "Blootgestelde hostpoort",                         "fr": "Port hôte exposé",                                "it": "Porta host esposta",                              "es": "Puerto de host expuesto",                         "pl": "Odsłonięty port hosta",                           "zh-cn": "暴露的主机端口"},
    "forceBroadcast": {                              "en": "Force Broadcast",                                 "de": "Übertragung erzwingen",                           "ru": "Принудительная трансляция",                       "pt": "Forçar transmissão",                              "nl": "Uitzending forceren",                             "fr": "Forcer la diffusion",                             "it": "Trasmissione forzata",                            "es": "Forzar transmisión",                              "pl": "Wymuś transmisję",                                "zh-cn": "强制广播"},
    "iface": {                                       "en": "Network Interface",                               "de": "Netzwerkschnittstelle",                           "ru": "сетевой интерфейс",                               "pt": "interface de rede",                               "nl": "netwerkinterface",                                "fr": "interface réseau",                                "it": "interfaccia di rete",                             "es": "interfaz de red",                                 "pl": "Interfejs sieciowy",                              "zh-cn": "网络接口"},
    "ip": {                                          "en": "Recipient IP",                                    "de": "Empfänger-IP",                                    "ru": "адрес получателя",                                "pt": "Endereço do destinatário",                        "nl": "adres van de ontvanger",                          "fr": "adresse du destinataire",                         "it": "indirizzo del destinatario",                      "es": "Dirección del receptor",                          "pl": "adres odbiorcy",                                  "zh-cn": "收件人 IP"},
    "net_setup": {                                   "en": "TCP/IP Network Settings",                         "de": "TCP/IP-Netzwerkeinstellungen",                    "ru": "Параметры сети TCP/IP",                           "pt": "Configurações de rede TCP/IP",                    "nl": "TCP/IP-netwerkinstellingen",                      "fr": "Paramètres réseau TCP/IP",                        "it": "Impostazioni di rete TCP/IP",                     "es": "Configuración de red TCP/IP",                     "pl": "Ustawienia sieciowe TCP/IP",                      "zh-cn": "TCP/IP 网络设置"},
    "port": {                                        "en": "Sender-Port",                                     "de": "Sender-Port",                                     "ru": "порт отправителя",                                "pt": "porta do remetente",                              "nl": "afzender poort",                                  "fr": "port expéditeur",                                 "it": "porta del mittente",                              "es": "puerto emisor",                                   "pl": "port nadawcy",                                    "zh-cn": "发件人端口"},
    "r_port": {                                      "en": "Receiver-Port",                                   "de": "Empfänger-Port",                                  "ru": "порт приемника",                                  "pt": "porta do receptor",                               "nl": "ontvanger poort",                                 "fr": "port récepteur",                                  "it": "porta ricevitore",                                "es": "puerto receptor",                                 "pl": "port odbiornika",                                 "zh-cn": "接收端口"},
    "serial": {                                      "en": "Serial Number",                                   "de": "Seriennummer",                                    "ru": "серийный номер",                                  "pt": "número de série",                                 "nl": "serienummer",                                     "fr": "numéro de série",                                 "it": "numero di serie",                                 "es": "número de serie",                                 "pl": "numer seryjny",                                   "zh-cn": "序列号"},
    "setup_info": {                                  "en": "Settings for Controllers, TCP/IP and Wiegand bus", "de": "Einstellungen für Controller, TCP/IP und Wiegand-Bus", "ru": "Настройки контроля доступа к дверям, TCP/IP и шины Wiegand", "pt": "Configurações para controle de acesso à porta, TCP/IP e barramento Wiegand", "nl": "Instellingen voor deurtoegangscontrole, TCP/IP en Wiegand-bus", "fr": "Paramètres de contrôle d'accès de porte, TCP/IP et bus Wiegand", "it": "Impostazioni per controllo accessi porta, TCP/IP e bus Wiegand", "es": "Ajustes para control de acceso de puertas, TCP/IP y bus Wiegand", "pl": "Ustawienia kontroli dostępu do drzwi, TCP/IP i magistrali Wiegand", "zh-cn": "控制器、TCP/IP 和 Wiegand 总线的设置"},
    "timeout": {                                     "en": "Timeout",                                         "de": "Auszeit",                                         "ru": "тайм-аут",                                        "pt": "tempo esgotado",                                  "nl": "time-out",                                        "fr": "temps libre",                                     "it": "tempo scaduto",                                   "es": "se acabó el tiempo",                              "pl": "koniec czasu",                                    "zh-cn": "暂停"},
    "wiegand_setup": {                               "en": "Door Access Controllers Settings",                "de": "Einstellungen der Türzugangs-Controller",         "ru": "сетевой интерфейс",                               "pt": "interface de rede",                               "nl": "netwerkinterface",                                "fr": "interface réseau",                                "it": "interfaccia di rete",                             "es": "interfaz de red",                                 "pl": "Interfejs sieciowy",                              "zh-cn": "门禁控制器设置"},
};